### ISSUE TITLE
Tag cloud (or tag browser)

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#123]
/tags/cycleparking
works but
/tags
doesn't.

This came to mind as now we have auto-complete in place, it would be good to tidy-up the historical data, but currently there is no listing which would make these obvious.

Should show a cloud of most popular, acting as a browsable index to tags.

Ideally have a complete index of all as well, but that is lower priority.

**Comment by mvl22** [comment]
It would be cool if each tag had a page that included a map, with each issue (or a thread within that issue) having its geometry shown.

Campaigners could then see the extent that a particular issue exists geographically.

**Comment by jf1** [comment]
I just went looking for something like this at /tags and rather than a tag-cloud I'd give higher priority to a complete list of all tags, showing each tag's frequency and sorted by most used. This would be very useful when assessing which tags should be encouraged and/or given icons, and also which should be combined eg 110x consultation and 18x consultations.

If external maps will show data based on tags then standardising some tags will be very beneficial. As for 'encouraging' these standardised tags, is there a way the auto-complete system could prioritise certain tags, eg cycle-parking and car-parking over the generic 'parking' ?

+1 to a map on each /tags/<tag> page... which is now possible using George's Issues Map code?

**Comment by jf1** [comment]
Please can someone reply to confirm that posts to a closed issue are read, ideally with a response to...

If there's no plan to implement a list of used tags at /tags then please can someone email me a csv of tags and frequencies, or paste the data here?

**Comment by mvl22** [comment]
> Please can someone reply to confirm that posts to a closed issue are read, ideally with a response to...

This issue isn't closed..

**Comment by mvl22** [comment]
Identified with @jf1 that implementing this issue would help group admins to start to consolidate tags with slight variations that should be the same thing, because the most common ones vs. the variants would be listed clearly in such a listing.

E.g. consultation / consultations - should be consolidated to one tag.

**Comment by mvl22** [comment]
I've been meaning to say for a while - the tag page is very slow to load, making it essentially not very useful. Can we add some indexing or something to make this appear more instantly?

**Comment by nikolai-b** [comment]
I've moved this to a new issue as I prefer to keep things separate.
