### ISSUE TITLE
Maps and Streetviews in individual comments

### ISSUE THREAD

**Issue by georgio8** [cyclestreets/cyclescape#256]
At present there is just one map associated with an issue. But it would be really useful to add additional maps and streetviews to the discussions. I know it can be done with links, but that is rather indirect and would involve the use of another map editor to add layers.

George

**Comment by smsm1** [comment]
For cycle paths etc where there is no Google Streetview, it would be useful to have the option of using Mapillary a newish crowdsourced street view.

**Comment by mvl22** [comment]
> For cycle paths etc where there is no Google Streetview, it would be useful to have the option of
> using Mapillary a newish crowdsourced street view.

Happy with this, but I think that is basically a separate feature request, and that we should concentrate on getting Street View as much higher priority.

**Comment by nikolai-b** [comment]
I'm not sure what is being asked for here.  We have Street View as a reply type now, is there something else?

**Comment by mvl22** [comment]
I was thinking a simple OSM map with a standard, unmodified, Leaflet.draw control, so that a map can be added to the thread.

The map position and optional drawn items would be saved in the database.

For instance, in a discussion, people could be suggesting a set of specific places for cycle parking within a wider scheme (for which the overall issue size is quite large). Or talking about a bit of a route through a housing area that is problematic as part of an overall much longer route.

Not sure what the e-mail equivalent should look like. Ideally it would render as a bitmap image attachment, but I imagine that's quite a bit of work, so it could just link to the posting for now.

**Comment by mvl22** [comment]
> I was thinking a simple OSM map with a standard, unmodified, Leaflet.draw control

I.e. this:

http://leaflet.github.io/Leaflet.draw/docs/examples/full.html

only with:

1) A slight adjustment to make the colour be standard Leaflet feature blue rather than pink, as pink is barely visible.

2) A working polygon interface - I think that example is temporarily broken as I get a wierd interface.

Basically just a stock Leaflet.draw interface. It saves a GeoJSON Feature Collection.

**Comment by mvl22** [comment]
The summary in My Cyclescape doesn't appear right - Nikolai, could you fix this as per previous similar problem?

![screen shot 2018-02-18 at 15 38 56](https://user-images.githubusercontent.com/361423/36353760-fa89acb4-14c1-11e8-9c16-44197678e30a.png)
