### ISSUE TITLE
Unsubscribe from followed threads using web-interface may not be clear

### ISSUE THREAD

**Issue by CHCausier** [cyclestreets/cyclescape#258]
I couldn't work out how to unsubscribe from a thread I was following on cyclescape for long enough to create a git-hub account to report it.

Edit:  Just found the greyed out button.  I was trying to click the green tick.  I also tried changing the thread priority to 'Not interested'

Tags: usability

**Comment by gravitystorm** [comment]
I've just found this too. Having the button greyed out isn't ideal.

Furthermore, there's an inconsistent use of "subscribe" and "follow" regarding threads. So when I looked at "my subscribed threads" and want to stop subscribing, I looked for an "unsubscribe" button rather than an "unfollow" button.
