### ISSUE TITLE
Multiple locations

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#309]
Issues often arise which affect more than one location and are best discussed together. We have two recent examples in Cambridge.

It would be very useful when reporting an issue to be able to specify multiple polygons, lines or points to define the area (or indeed a mixture), rather than the single one you're limited to at the moment. Otherwise either the discussion gets fragmented, you end up defining a huge generic area encompassing all of them, which is overkill, or people who'd like to know about it don't get to know.

**Comment by mvl22** [comment]
Spotted in the Leaflet.draw documentation (which I believe we're now using):

```Leaflet.draw does not work with multigeometry features such as MultiPoint, MultiLineString, MultiPolygon, or GeometryCollection. If you need to add multigeometry features to the draw plugin, convert them to a FeatureCollection of non-multigeometries (Points, LineStrings, or Polygons).```

https://github.com/Leaflet/Leaflet.draw

**Comment by nikolai-b** [comment]
My initial thought on this is that the interface has a new option at the bottom: "Add another" which is visible only when one feature has been completed.  When selected then the user can draw another shape using the same controls and when the second feature is finished the second shape is selected for editing.  To allow the user to edit the first shape then an "Edit other feature" would also need to be added to the interface (this could cycle through features or allow the user to select a feature to edit).  Do we want to allow unlimited number of separate features?

**Comment by mvl22** [comment]
I would stick fairly closely to the standard Leaflet.draw UI:
http://leaflet.github.io/Leaflet.draw/

though I'm not a fan of the Save/Cancel system - I think changes should take effect immediately, so that what is on the screen is always the current state that would be saved if the form were submitted, but with an undo to deal with problems.

**Comment by jf1** [comment]
> Do we want to allow unlimited number of separate features?

10 would be an acceptable limit for me, although I could imagine that someone who regularly cycles in eg 12 wards may like to add them all.

The ability to edit shapes would be appreciated, and an undo feature would be a bonus (rather than an alternative to editing).

Any recent progress or imminent plans to implement gpx uploads #524, routing #95, and administrative boundaries or Cyclescape group areas #584/#174 ?

There's also a request for area descriptions (this could be for the FeatureCollection not each geometry within it) that I've highlighted in new ticket #635 along with a request for the ability disable an area (or its notifications).

**Comment by davidearl** [comment]
Why an arbitrary limit? If there's an artificial limit on something for
implementation reasons, there's always some case that comes along that
needs one more.

**Comment by jf1** [comment]
I wasn't making the case for implementing a limit, just offering feedback on what limit would be acceptable for me should one be implemented. Please handle FeatureCollections however you see fit.

Imho the ability to add areas/lines without having to manually draw them is much more important - the current lack of this feature regularly hinders my use of Cyclescape.

**Comment by mvl22** [comment]
Can you change the line colour - the current Leaflet.draw pink is barely visible.

See the issue upstream about this:
https://github.com/Leaflet/Leaflet.draw/issues/642

**Comment by mvl22** [comment]
Seems to work nicely - good work.

It would be nice in future to be able to clear individual items after drawing, but I think this is fine to go live for this to be considered later.

**Comment by mvl22** [comment]
> Can you change the line colour - the current Leaflet.draw pink is barely visible.

The new blue is still very light. I'm amazed you can see it clear. If you try in a busy map area like Cambridge it is far from clear.

Can you try the HTML colour DarkBlue, i.e. #00008B - that should be good enough.
