### ISSUE TITLE
Allow users to hide their profile

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#316]
Refs #218 

> [...] there should be a setting:

> My profile page [include link to it] is:
> (•) Visible to anyone
> ( ) Visible only to members of groups I'm in

> Probably 'Anyone' would be the default, because the display name stuff above already adds a degree of privacy.

> Additional implementation would be needed:

> *  Profile page should behave like a standard 404 when not viewable, rather than give some indication that someone might be present
> *  When the profile page is not active, mentions of the visible name around the site should be text, non-hyperlinked.

**Comment by mvl22** [comment]
I've had a look at the changes on the issue-316 branch, testing out different scenarios (which involved quite a bit of tab opening!).

On the specific aspect of profile visibility, I propose the following distinct changes:

**1) Disabled profile should actually returning 404, not HTML page**

If I go to
http://www.cyclescape.org/users/5-martin-lucas-smith/prefs/edit
and set
Profile visibility = Only members in my groups
then viewing that profile:
http://www.cyclescape.org/users/5-martin-lucas-smith/profile
in a context where the profile is hidden (i.e. in incognito mode (i.e. guaranteeing I am not logged in); or as another user who is not in my groups)
currently results in an (unimplemented!) message:
"Profile Hidden
Profile Hidden Guidance"

This should instead be a 404, so that there is no way to determine if a user exists by guessing their URL.

(This definitely should then have a test added, as future breakage of code for this kind of thing should be considered critical.)

**2) Labelling change to radiobuttons**

I think the following labelling change would be more standard English. Change, on 
"Only members in my groups"
to
"Only members of my groups"

**3) Move profile privacy preference to profile editing section**

Currently the profile privacy is set at /users/5-martin-lucas-smith/prefs/edit (the block headed "Profile visibility"), which is really intended as a page concerning subscription preferences. The mixing of the two things is not helpful on an already complex page. There is a separate profile editing page (accessed via the "Edit my profile" button in the submenu), at /users/5-martin-lucas-smith/profile/edit .

Therefore, could you move that "Profile visibility" block to the "Edit my profile" page, so it is the first control. I realise this will presumably need a data migration, as presumably each page maps to a database table. (However, I think it makes more sense to have the profile visibility flag within the profile settings anyway.)

**4) Then rename "Manage My Preferences" page to "Subscription preferences"**

Having moved the profile stuff out of the subscription preferences area, we can now fix up its name. I suggest "Subscription preferences".

**Comment by mvl22** [comment]
Thanks - this stuff all looks good now, and can all go live.

**Comment by mvl22** [comment]
Hmm.. actually I'm getting an error 500 if I submit the profile form, on my local dev machine:

```
Started PUT "/users/5-my-real-name/profile" for 10.0.2.2 at 2015-05-25 21:08:11 +0100
Processing by User::ProfilesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"E5kSpxy6iVU6WW4SyOPLoGzwG7oZHgHmYyDHIXBtRlc=", "user_profile"=>{"retained_picture"=>"", "remove_picture"=>"0", "website"=>"", "about"=>"- Some text", "visibility"=>"public"}, "commit"=>"Save", "user_id"=>"5-my-real-name"}
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 5 AND ("users".deleted_at IS NULL) LIMIT 1
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 AND ("users".deleted_at IS NULL) LIMIT 1  [["id", "5-my-real-name"]]
  UserProfile Load (0.7ms)  SELECT "user_profiles".* FROM "user_profiles" WHERE "user_profiles"."user_id" = 5 LIMIT 1
   (0.1ms)  BEGIN
   (0.2ms)  ROLLBACK
Completed 500 Internal Server Error in 18.2ms
```

This happens each time I try.

**Comment by mvl22** [comment]
This did seem to be fine after a subsequent commit.

**Comment by nikolai-b** [comment]
Done in #369
