### ISSUE TITLE
Ability to search for keywords in planning applications

### ISSUE THREAD

**Issue by smsm1** [cyclestreets/cyclescape#360]
It would be useful to be able to search for e.g. parking or cycle parking, so that you can find planning applications that will be interesting to look at quickly.

**Comment by mvl22** [comment]
@nikolai-b This is one reason I am interested to tie this into the general search - it becomes a unified facility which looks at everything, whether issues, discussion threads, library items, tags, planning applications, etc.

**Comment by nikolai-b** [comment]
Can we be clear about what you want?  I think you want to have a list of planning applications with some weight being given to the start time and some weight being given to the name and description so that the relevant ones appear first.  Ideally a system that learns.
Have a search will not help here, if you search for 'bicycle' you will see any planning application (from the possible 30 000) all over the UK with 'bicycle' in the title or description.  Or I can make it so you only see the ones in your current area but then you cannot search globally for the planning reference nos. (which is very useful).
If we are interested in building a system that will show relevant planning applications (ideally with a Genetic Algorithm) lets do that, I will close this issue and open another.  If you want me to add it to the global search I can but I strongly think you will be disappointed with the mess it creates and time it takes.

**Comment by smsm1** [comment]
Global search wouldn't be useful, just the ones in the current area. A genetic algorithm would be interesting, as it would over time learn the type of application that is ignored/voted down.

**Comment by nikolai-b** [comment]
But without a global search you can't search by planning reference (the reason I added a search).  Glad you like the idea of a genetic algorithm, it seems like that (combined with user voting) will give everyone what they want.  Its a big-ish job so will have to think about it

**Comment by smsm1** [comment]
Are the planning references unique globally? Is there potential for the references to be the same in the 2 different areas. 

I'm thinking an option to highlight planning applications or limit the search to the local authorities or areas that you are interested in. For example, I'll primarily be interested in planning applications within Ipswich and the surrounding area, and not others on the other side of the country.

**Comment by nikolai-b** [comment]
> Are the planning references unique globally?
Yes.
I'm closing this.  When we have time an resources I think a Genetic Algorithm is the way to go.
