### ISSUE TITLE
signature.asc attachments should be stripped automatically

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#417]
One author's e-mail on this thread replies by e-mail which includes a signature.asc file, resulting in a second message.

http://camcycle.cyclescape.org/threads/2106

It's obviously quite reasonable that people should include these, so I think the system should detect these and throw them away without comment or other action.

**Comment by wookey** [comment]
Right. I recently turned on signed email. So that attachment is a standard gpg multipart mime signature. 

The correct way to identify these is by looking for 
Content-Type: multipart/signed;  (i.e not the filename 'signature.asc' which is almost certainly application-specific)
The header includes other stuff, including:   protocol="application/pgp-signature"; which may be how you identify which of the mime parts is the one to be binned.

Does cyclescape currently take all attachments and make them into separate posts? 
Clearly it shouldn't be posting sigs as separate mails. It would be best if the sigs were left with the mail so that list recipients could tell that the mail really was from who it said it was, This works fine because only the body is signed, not the headers. So majordomo passes on signed mails as expected.
Cyclescape should do the same and leave the mail body alone and leave the sig as the same multipart attachment it came in as.

Note that sigs can be inline as well as multipart MIME. Any idea what currently happens if you send those?

**Comment by mvl22** [comment]
Thanks - very useful. We'll try and get this in ASAP.

**Comment by nikolai-b** [comment]
Done in https://github.com/cyclestreets/cyclescape/commit/888bf3fab207459697681c757923899f1fa01405
