### ISSUE TITLE
'Welcome & next steps' e-mail needed

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#425]
At present, a membership approval doesn't actually result in an e-mail to the applicant.

Because email is not the default, and geographical areas aren't defined by default, if you approve but don't contact them, as far as they are concerned nothing they go into a black hole. In Cambridge, they are currently always followed this up with an email about what to do next (pointing out the e-mail and geographical areas aspect), but the system should do this instead as standard.

(Possibly this is a duplicate of a previous issue, as this has been a problem for a while.)

**Comment by mvl22** [comment]
@davidearl Could you post here the current e-mail so that we can make this into the auto-sent mail?

**Comment by davidearl** [comment]
OK, see below.

However
(a) I still think it would be much better to have email on by default - it's much easier to realise you have to turn it off if you don't want it that vice-versa
(b) I really think the area should be defaulted to the group area (very occasionally more than one if they are in more than one group). Marking out areas is one thing people consistently miss the steps for (even though they are really prominent) and fail to complete. Again this is much more fail safe - they can always redefine them, but if they don't know how to get them in the first place they are in limbo
(c) it would be best if the message is configurable by group.


Subject: Cyclescape, Cambridge Cycling Campaign's discussion forum [so that they know what we're talking about - don't assume they know what Cyclescape is or does]

Dear <whoever> [personally addressed is better for spam avoidance and much more liklely to be acted on by the recipient]

I'm about to send you an invitation to Cyclescape, our discussion forum, as you requested.

When you accept, you will want to do two things in particular:

(a) mark on the map provided where is of particular interest to you, so you get notified when there is a discussion going on relevant to that area

(b) check your preferences, in particular you probably want to tick the email notification box at the bottom of the preferences page, or you won't get any email for ongoing conversations ("threads") from Cyclescape.

You can opt-out of a conversation if it gets too much for you, without dropping out of other conversations; or you can use the whole system from within the web site.

You might also want to follow us on twitter @camcycle.

Regards,
Sue
membership secretary

**Comment by mvl22** [comment]
> I still think it would be much better to have email on by default

Yes, that is issue
https://github.com/cyclestreets/cyclescape/issues/198

The sending of an e-mail is needed either way, whatever the outcome of that discussion.

**Comment by mvl22** [comment]
> it would be best if the message is configurable by group.

Yes, good suggestion. Or perhaps standard text followed by a space for additional comments, as that will ensure that all users receive a consistent message that will make managing support queries easier.

**Comment by mvl22** [comment]
> (b) I really think the area should be defaulted to the group area

Point moved to #198.

**Comment by nikolai-b** [comment]
A welcome email has been added in bf37962 for all new users
A group editable (in group profile) one has also been added when a user joins a group e9e6848 (the text `{{full_name}}` is interpolated to be the users full name)

**Comment by mvl22** [comment]
Thanks; will review and adjust the text.

**Comment by nikolai-b** [comment]
In production now, do you want to email group committee members about this _exciting_ feature?

**Comment by mvl22** [comment]
May do, after seeing how well it works in the group I'm personally in.
