### ISSUE TITLE
Support multiple domain names to enable international sites to run from single main installation

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#482]
We've had another request for help setting up an international version of the site.

However, in my view it would be strongly preferable if the main UK installation which CycleStreets maintains could support international sites.

1) This would make it easier for new groups around the world to get set up (as they wouldn't need technical knowledge). This would probably also help bring funding more easily too.

2) It avoids satellite installations getting out-of-date or ending up with divergent code that doesn't get committed upstream. There are commits in:
https://github.com/auto-mat/toolkit/commits/deploy
which I think aren't in the main repo.

3) It would make it more likely that open source contributions will come forward as there is a lower barrier to entry of people using the system.

4) It would mean that things like library items and other knowledge gain cross-border co-operation, rather than having multiple silos of information.

5) Having the main installation ending up with issues across Europe for instance would provide evidence for decision-makers about common problems.

6) It increases the changes that sites will be well-run, e.g. backup, security updates, governance.

As far as I can see, the main requirements would be:

1) Support multiple domain names, where www.* is treated as exactly the same thing in terms of users using the system in an ungrouped mode.

2) Add support for switching the name, logo, etc. on the basis of the main part of the domain name. See also issue #433 on this, which gives a more complete list, but these all seem like things that shouldn't be hard-coded anyway and should be settings instead.

3) For groups, set the domain name + subdomain as the unique constraint for a group in the database rather than just subdomain.

Anything else? @nikolai-b @PetrDlouhy - do add your thoughts.

**Comment by PetrDlouhy** [comment]
Hi,

the changes on our branch aren't in fact so big. The biggest portion is translation (that is in PR #477). For few other things I made a PR now.
The rest are thing mentioned in #433, which are I changed in code, but should be made into config.

The convergence of the code is clearly the first thing, we should do. This only gives extra requirement, that the configuration should be from user interface (not just local config).

Running your service worldwide with local adjustments is something, that you can greatly benefit from. Especially, if you make the site more user friendly. So I think, that you should do that.
I am not sure, if you get more code contributors that way, because they will be less motivated and involved, if they don't run their own installation.

Another question is, if we can transfer our site to your server. There are some questions about the ownership and control over the data. I can imagine that, but we would have to discuss that with our colleagues.

**Comment by gravitystorm** [comment]
It's not clear what's meant by "international version" since Cyclescape already works for issues, groups and conversations located anywhere on the globe. 

I'd advise taking a step back and rethinking. You say "international sites" but I think the "international" label is just misleading - they are just "separate installations" for a variety of reasons, and it's best to sort those reasons out directly.

As far as I'm aware, the reasons for separate installations of cyclescape so far has been 90% translations and 10% configuration tweaks. If we were to improve the experience for non-English speakers (regardless of location or group, e.g. spanish speakers in the UK), and allow groups more flexibility in configuration (again, regardless of location), wouldn't that solve the reasons of separate installations?

**Comment by mvl22** [comment]
> As far as I'm aware, the reasons for separate installations of cyclescape so far has been 90% translations and 10% configuration tweaks. If we were to improve the experience for non-English speakers (regardless of location or group, e.g. spanish speakers in the UK), and allow groups more flexibility in configuration (again, regardless of location), wouldn't that solve the reasons of separate installations?

Yes, that was my thinking exactly. By parameterising the differences, we can avoid the need for people to spend time having to maintain separate versions and ending up with data silos.

**Comment by mvl22** [comment]
> This only gives extra requirement, that the configuration should be from user interface (not just local config).

Yes; I agree. The sort of config discussed would clearly need to be set via a webform within the admin area.

> I am not sure, if you get more code contributors that way, because they will be less motivated and involved, if they don't run their own installation.

I think they would be more motivated. There are two separate installations involved: (1) the live site, which basically needs effort/money/etc. to maintain and which I'm suggesting would no longer be needed, and (2) a local installation on the developer's computer, which will be needed either way.

The reason I think that more code contributors is more likely is that if the main installation can support multiple domain names and branding, new cycle campaign groups from different countries around the world will be able to start using the system without needing the complex Rails/chef/Linux/etc. knowledge to set up a server. Having created a site and branded it to their own language (e.g. Cyklisté sobě - Cyclescape makes no sense in Czech), they will have users, and amongst those users will be programmers.

> Another question is, if we can transfer our site to your server. There are some questions about the ownership and control over the data. I can imagine that, but we would have to discuss that with our colleagues.

Yes, naturally.

**Comment by nakic** [comment]
Can definitely confirm from experience over the last few weeks that it is a very bumpy ride, getting cyclescape installed even onto a dev. environment, let alone a production env (that coming from a relatively experienced SW developer familiar with linux, DevOps...although not ruby). The opportunity to create a local group on an existing site, customise etc. would be very welcome, at least to begin with.

**Comment by nikolai-b** [comment]
I'm not sure what is left with this issue.
I've not done:

> For groups, set the domain name + subdomain as the unique constraint for a group in the database rather than just subdomain.

But given the site doesn't use multiple domains I'm not sure this is the place to start doing that until we need to.

**Comment by nikolai-b** [comment]
Let's close this and if there is another feature that is missing can we open it up in a new issue?
