### ISSUE TITLE
Populating Issues from Planning applications

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#607]
When a planning application is converted into an issue it currently uses the planning application's description.  This is often too long.

Suggestions have been to truncate or use the planning application UUID but @mvl22 is not in favor.
https://github.com/cyclestreets/cyclescape/pull/605

How about we leave the title blank?  To me that makes more sense as the issue description will be pre-filled but the title probably requires some more thought.

**Comment by jf1** [comment]
I agree with @roxannedebeaux's original point - if there's isn't an auto-updating character count then pre-populating the input field with too many characters is problematic.
And I agree with @mvl22 that the UID isn't particularly useful.
And with apologies to @nikolai-b, blank might be easy to implement but it's also far from ideal.

There were two points made in #603 - knowing when over the current limit of 254 characters (ideally by how much); and should titles longer than 80 characters be discouraged or prevented.

Currently 24 characters are prepended: "Planning application : " and this could be reduced to 11: "Planning: "

I'm fine with 254 character titles so would support a simple fix of pre-populating the title with "Planning: " then the first 243 characters from the planning application's description. Obviously this suggestion could be implemented with fewer characters and/or a smaller limit.

However I'd prefer the more elegant option of an unlimited text input field (ideally a resizeable area box rather than a single-line field) with a character count system similar to twitter's - two examples [here](http://stackoverflow.com/questions/29582824/textarea-counter-countdown-with-negative-numbers-and-enforcement). Those examples show a negative number and disable the submit button when the character limit is reached but there should also be a server-side check during submit to trap cases of long titles from users without (or who've tampered with the) javascript.

**Comment by mvl22** [comment]
> And I agree with @mvl22 that the UID isn't particularly useful.

Sorry if I implied that - I think it *is* useful, but only as part of a clear overall description.

> Currently 24 characters are prepended: "Planning application : " and this could be reduced to 11: "Planning: "

I think it should stay as Planning application as the default. Planning doesn't really explain what it is.

**Comment by roxannedebeaux** [comment]
I would like to see a different method altogether for distinguishing
planning applications rather than in the title, along with suitable
management and tracking tools. They are consistently falling through the
cracks as there are insufficient management features.

I can see people struggling with the input field unless it is made very
clear what is happening. I agree with jf1 that the Twitter method is ideal.


Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join: *camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *Text "CYCC11 £5"
to 70070
*Charity no. 1138090*

**Comment by jf1** [comment]
@mvl22 I should apologise for omitting 'alone' - to clarify, I was suggesting that the UID on its own wasn't ideal, and agree it's useful when with other details. The shorter prefix of "Planning: " was just an idea to help with shorter titles, and it wouldn't cause any confusion for me as planning applications would be the default cyclescape issue with "planning" in the title - I'd make rarer eg "meeting planning" type discussions use longer descriptions.

re "falling through the cracks as there are insufficient management features" - automatically adding the consultation end date would help, as requested in #372

**Comment by roxannedebeaux** [comment]
I don't think the automatic shortening of planning application titles is
working.

It would be better to at least bring the info over to assist in getting the
relevant info included.

There are not enough characters to ensure an informative title. We either
need to remove/shorten "Planning Application" or provide more information.

I've just created an issue with a pointless title as I didn't realise it
had cut everything off.


Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join: *camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *Text "CYCC11 £5"
to 70070
*Charity no. 1138090*

**Comment by nikolai-b** [comment]
Is there a clear consensus about what to do with this?

**Comment by mvl22** [comment]
> I've just created an issue with a pointless title as I didn't realise it had cut everything off.

NB This is exactly why I am against automatic chopping.

**Comment by jf1** [comment]
I don't think this implementation will be intuitive for users.

It's currently not possible to see all the title text at once, hence suggesting this input field is a resizeable area box rather than a single-line field.

And rather than require users to react to the server-side rejection of titles >76 characters, a twitter-style live character count would help users submit a short enough title - I would much prefer this feedback while editing the title rather than after submitting it.

**Comment by nikolai-b** [comment]
@jf1 commits here appear in the staging server (which I believe you have access to).  The live update is exactly what I've done in https://github.com/cyclestreets/cyclescape/commit/bd92c9d0.  I believe the limitation on the title box is intended as we do not want long titles, if you disagree please open a new issue :smile: .
