### ISSUE TITLE
Search on map not working to set up new issue. 

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#631]
Trying to set up a new issue and put the location in. When the location is found the map does not move to it. Currently unable to set up the issue without the location. Can't set the location...

**Comment by roxannedebeaux** [comment]
Currently unable to post this issue: https://idox.cambridge.gov.uk/online-applications/applicationDetails.do?activeTab=documents&keyVal=OCH0EXDXFMH00

**Comment by mvl22** [comment]
@nikolai-b This is almost certainly a regression in c9828f153768ef76c7280976f2b16b4a2a982cb6 presumably.

Clicking on a search-as-you-type result gives `Uncaught TypeError: Cannot read property 'lat' of null` in the console.

Drawing the location works fine and enables the issue to be submitted.

Anyway, planning applications should be having their location set automatically anyway, but this also seems to have broken.

NB Not sure how much of this would be possible to get within the tests :(

**Comment by nikolai-b** [comment]
Planit doesn't have the lat or lon of that application
http://www.planit.org.uk/api/applics/json?limit=30&start_date=2016-08-12&end_date=2016-09-19&id_match=16%2F1566%2FFUL so that is why it isn't pulled in.  I agree adding automated tests would be very time consuming.  I'm hoping that https://github.com/cyclestreets/cyclescape/commit/1c1ae0cc705993e61dc13fd36ef9c92cba5fbe7c is the last major js change for a while.

**Comment by mvl22** [comment]
If we don't have the lat-lon, can the interface say as such, e.g., "We don't have a map location for this planning application. Please set it on the map."
