### ISSUE TITLE
Mailbox icon in top-right should light up when a direct message is not yet read

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#656]
We now have the mailbox icon which provides a direct link to direct messages.

Next stage of iteration of this feature is to have it light up when there are unread messages.

Ideally there would also be an iOS / Facebook -style red circle containing a number showing the number of messages. I suppose we would need to decide whether that means threads or messages. Threads is probably OK as a start.

There has been a user request on this.

![ios-number](https://cloud.githubusercontent.com/assets/361423/20440081/610b5236-adb6-11e6-9d13-540c99d5ab19.jpg)

**Comment by jf1** [comment]
I don't feel there's much extra benefit from a number instead of a light but I can see how it's a "nice to have" feature that does no harm (unless it leads to any layout issues). Displaying the number of updated threads (as per gmail) would always be my preference over displaying the total number of new messages.

**Comment by mvl22** [comment]
Duplicate of #690, now implemented.
