### ISSUE TITLE
Committee members should always be auto-subscribed to new administrative threads

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#696]
When a new administrative discussion thread is created for a group, Committee members should always be auto-subscribed to it.

This can be implemented by the equivalent of auto-ticking the "Also involve me in my group's administrative discussions" threads checkbox in their subscription preferences at `/settings/preferences`. (They can undo this if they want, but this is unlikely.)

When a Committee member is demoted to a normal member, that tickbox can stay as it is. The only thing that should need to change as a result of this ticket is just auto-ticking the box when a person becomes a Committee member.

This should remove complaints about Committee members being unaware of admin stuff that they should be party to.

**Comment by jf1** [comment]
Please consider expanding this so that when a standard user is added using the API as requested in #683 they can also be set to auto-subscribe to a group's administrative threads. Obviously the user could later change their own setting should they wish.

If #523 was implemented then the ability to auto-subscribe during user setup (and ideally opt-in/out of a category via the API) would be excellent.

It would also be useful if a group administrator could opt someone into admin or categorised threads, or at least trigger something that the user confirm, so that group admins can properly assist and/or manage their users.

**Comment by mvl22** [comment]
@jf1 Please can you create these separate proposals as new issues.

**Comment by nikolai-b** [comment]
@mvl22 do you also want a data migration to set all current committee members to get admin discussions?  This could be controversial as some may have explicitly opted out...

**Comment by mvl22** [comment]
Yes, please run a migration.

**Comment by mvl22** [comment]
Great!
