### ISSUE TITLE
Double e-mail subscriptions

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#711]
We're getting reports of people now getting double e-mails since the change to fix #701.

@nikolai-b, is it possible that this is caused by the asynchronous subscription system now?

See the user report at `/threads/227#message_41331` and feedback 2598 at `/site/comments`.

**Comment by nikolai-b** [comment]
Are you getting duplicates @mvl22 ?
Could it be some users only?

**Comment by mvl22** [comment]
Oddly, I'm not seeing this myself. Sorry, should have said.

**Comment by nikolai-b** [comment]
So the thread the user is referring to isn't in the backup so I can't check that yet but I can't easily reproduce this locally yet.  Could you find out some more information about the messages that have been duplicated?  What exactly were they, were they sent at the same time?

The fix to #701 moved the job of subscribing users to the thread to the background so if the duplicate message is a  new thread notification then it is likely caused by this change.

I've tried locking the thread to prevent this but I can't be sure without a bit more info esp. timing so I can dig into the logs.

**Comment by nikolai-b** [comment]
I've spent a while looking at the logs and I can't see this happening to the user mentioned in `/threads/227#message_41331`

**Comment by nikolai-b** [comment]
Can you ask them to forward the emails to me / you?

**Comment by mvl22** [comment]
Presumably the same thing as #712. E-mail problem is now resolved.
