### ISSUE TITLE
Inconsistent presence of unsubscribe links in e-mail

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#727]
User feedback (no. 2609):

> Why do some emails have unsubscribe links at the bottom, and others don't?

**Comment by nikolai-b** [comment]
Any more info?

**Comment by mvl22** [comment]
@davidearl Are you able to give any more details?

**Comment by mvl22** [comment]
I haven't seen this myself - I think it's correct now. Feel free to re-open if not.

**Comment by davidearl** [comment]
I've not seen precisely this since. There is an issue with GMail/Inbox though, in that it suppresses previous content that's duplicated in later messages, so if (as often happens, eg adding a deadline) there are two emails in quick succession, you have to either hunt back in the earlier email for the link, or open up the duplicated part (there are ellipses in gmail for the redacted content), so it's rather laborious to get to the link. Add to that that you almost always also get a New Issue email, and that usually arrives later, there's often already 3 emails before I can start suppressing them.  And on a day when planning applications are added, I find myself having to do this many times.

**Comment by mvl22** [comment]
>  so if (as often happens, eg adding a deadline) there are two emails in quick succession

Do you mean perhaps that the e-mail that is emitted when a date/deadline is added doesn't have this? I'm not clear why later messages should hide the link, if each individual message does have it.

**Comment by davidearl** [comment]
That is a function of GMail. GMail and Google Inbox redact repeated parts of the email in a thread. It's not something Cyclescape is doing, but it means the links aren't easy to find in GMail.

**Comment by mvl22** [comment]
Ah, OK. Doesn't sound like there's much we can do about that - this seems to be a client display issue.

**Comment by davidearl** [comment]
Well, there is, and not just because of this slight quirk in gmail, but that would reduce the onslauight of email from cyclescape in general, and that is to spot the common idiom of: new issue - new thread - set thread deadline - which generates three separate emails, and combine them in one. In general I'd like it if emails about one thread were bundled rather than being sent out for every change.

**Comment by mvl22** [comment]
> new issue - new thread

See #660 which will fix that.

> In general I'd like it if emails about one thread were bundled rather than being sent out for every change.

Feel free to propose that in a new issue. Would need to consider how long it might have to wait before deciding there won't be more postings, but that's a different question than this ticket.

**Comment by nikolai-b** [comment]
I think Gmail is a large enough client that we should fix this.
I really simple solution would be to move the 

> Cyclescape discussion thread:
>  http://www.cyclescape.org/threads/xxx#message_yyy

to the bottom of the signature.  As that is unique I believe Gmail will not hide it.
