### ISSUE TITLE
Posting to thread should have AJAX interception

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#769]
Currently, a posting to a thread results in a traditional POST-reload HTTP pattern.

However, it would be good to have AJAX interception and loading of the newly-posted message to the thread via AJAX (but with the traditional method remaining for accessibility).

This would make the message appear quicker and feel more responsive, and avoid the long scroll-down during the reload also.

**Comment by nikolai-b** [comment]
Multipart forms cannot be easily submitted using AJAX.
I can use something like this https://github.com/JangoSteve/remotipart but do we need files and images to be submitted via AJAX?

I've set this to jump to the top of the page if there is an error with the submitted content (so the warning is clear) otherwise it will just clear the form and add the message.  This is merged into staging.

The other option would be to have the warning float with an cross but I think that is over the top.

**Comment by mvl22** [comment]
Let's start with the text one and worry about the others later - this will improve things for 95% of the postings.

**Comment by mvl22** [comment]
I think this isn't updating the last-read status for each thread. I posted to a thread, and it successfully used the AJAX method, but the Overview page shows the thread in blue, indicating that the message I myself posted is supposedly unread.
