### ISSUE TITLE
Emails need to be stored as HTML

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#826]
Now we are storing message in HTML the emails need to be also converted to HTML.

We storing and displaying the plain text part of the email but really we want to use the HTML part if it is there. This needs a clever way of detecting quoted text in HTML (and also email signatures).  So far I've found https://github.com/lever/planer but the signature tools all look to be plain text.

If the email is plain text we should use the same conversion we used when displaying plain text previously.

**Comment by nikolai-b** [comment]
@wookey I've manually updated messages that look like plain text:

```ruby
html_format_time = Rails.cache.fetch("html_format_time")
h = ActionController::Base.helpers
Message.where("created_at > ?", html_format_time).where.not("body ILIKE '%<p%'").where.not("body ILIKE '%<div%'").where(component_id: nil).each do |mes|
  parsed = EmailReplyParser.read(mes.body)
  stripped = parsed.fragments.select { |f| !f.hidden? }.join("\n")
  mes.update!(body: h.auto_link(h.simple_format(stripped)))
end
```

so they should look a bit better on the web interface.  Please let me know if there are any that remain strange.

**Comment by nikolai-b** [comment]
I think https://github.com/cyclestreets/cyclescape/commit/d3802760df492cdff02f01c1617a5344cb352ced along with a few more commits should have fixed this but I'm not entirely confident I've covered all cases.

**Comment by wookey** [comment]
On 2018-12-15 08:45 -0800, Nikolai wrote:
> @wookey I've manually updated messages that look like plain text:
> 
> html_format_time = Rails.cache.fetch("html_format_time")
> h = ActionController::Base.helpers
> Message.where("created_at > ?", html_format_time).where.not("body ILIKE '%<p%'").where.not("body ILIKE '%<div%'").where(component_id: nil).each do |mes|
>   parsed = EmailReplyParser.read(mes.body)
>   stripped = parsed.fragments.select { |f| !f.hidden? }.join("\n")
>   mes.update!(body: h.auto_link(h.simple_format(stripped)))
> end

OK. I don't speak rails or ruby, so not quite sure what that's doing,
but incoming mails are _marked_ as plain text or multipart
text/html. Can you not use that info to make sure they are correctly
processed? i.e either preserved as text (and put into <pre> for
html-viewing?) or used as html/multipart as-is (and a text version
generated if (incorrectly) empty) (and the html version displayed in
the webUI). Perhaps I don't understand something about how the
processing is done?

> so they should look a bit better on the web interface. Please let me know if
> there are any that remain strange.

Just to be clear I don't generally use the web interface. I get emails
as text and I reply to them as text. I sometimes use the web inteface
to get a related media doc or image (but only because the URL for that
media does not come through in the emails SFAICS - be nice if it did).

I also have to use the web interface because it seems to be impossible
to start a new topic from email. 

I just had a look and the HTML view of https://www.cyclescape.org/threads/4326
looks fine (well, the view reflects the emails sent).

Wookey
-- 
Principal hats:  Linaro, Debian, Wookware, ARM
http://wookware.org/
