### ISSUE TITLE
Unable to set "My Location"

### ISSUE THREAD

**Issue by mattturner86** [cyclestreets/cyclescape#845]
I've just deleted all of my locations, intending to add a new one after, but the location webpages are failing to load correctly.
Both the "My Locations" page and "Edit Location" page are returning Javascript errors.
These pages were loading fine before I deleted my locations.

username: mattturner86@gmail.com
Browser: Chrome (73.0.3683.86) and Edge (42.17134.1.0)

I've included a screenshot of both pages as well as the Javascript console error for each (which seem to be the same)

https://www.cyclescape.org/settings/locations
![image](https://user-images.githubusercontent.com/5785268/55671289-9c245700-5886-11e9-9e21-f94da60dfeb7.png)
![image](https://user-images.githubusercontent.com/5785268/55671268-4cde2680-5886-11e9-90ac-b7d6c1ca8d5e.png)

https://www.cyclescape.org/user/locations/new
![image](https://user-images.githubusercontent.com/5785268/55671285-8878f080-5886-11e9-82c2-9cb886ab32b7.png)
![image](https://user-images.githubusercontent.com/5785268/55671271-5798bb80-5886-11e9-9125-0fea5387c49f.png)

Thanks!

**Comment by nikolai-b** [comment]
Thanks @mattturner86 , we should have been treating empty features (locations) as invalid but a while ago we allowed changed to accepting a collection of features, instead of just one feature, and the test if a collection is empty is a bit different and was overlooked.

I've deployed the new code and ran
```sql
DELETE FROM user_locations WHERE ST_IsEmpty(location) = 'T';
```
to delete any existing empty locations.
