### ISSUE TITLE
"Find group by name or postcode" search box not working

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#846]
nothing happens with 'enter' or clicking 'go'

**Comment by nikolai-b** [comment]
Hi,

I've just tested and it works for me
![Screenshot from 2019-04-20 22-29-27](https://user-images.githubusercontent.com/6289830/56462491-ccf2a900-63bb-11e9-9359-0df9846d3c8f.png)

Mind adding a screenshot or what you entered?

**Comment by mvl22** [comment]
So, the problem here is that if there are no results, that is not stated.

![Screen Shot 2020-01-02 at 22 25 42](https://user-images.githubusercontent.com/361423/71697113-de93a980-2dae-11ea-9acc-a1e411ac7df8.png)

![Screen Shot 2020-01-02 at 22 25 52](https://user-images.githubusercontent.com/361423/71697112-de93a980-2dae-11ea-8362-d1b352263eb7.png)

What needs to happen is that the box underneath needs to show as per when there are a results, with "No results".

**Comment by mvl22** [comment]
This is working fine.

Does this new string need to be added to the translation file?

**Comment by nikolai-b** [comment]
No because the [HTML](https://github.com/cyclestreets/cyclescape/blob/1c3adb04313f774c911251cbd696e280edc340ff/app/views/groups/index.html.haml#L14) view already uses it [no_results_found](https://github.com/cyclestreets/cyclescape/blob/676964c1abbb92fbe08568c099e3f5be1f0df9e1/config/locales/en-GB.yml#L468) is in the translation file already.
