### ISSUE TITLE
Set a location for a library item

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#86]
Library items have a location column, but no mechanism for setting it or using it. This could become useful in future when geographically-relevant items are required.

**Comment by mvl22** [comment]
So basically this needs the same map location fragment added as currently used in:

/issues/new
/user/locations/new

including the search box within that panel

**Comment by nikolai-b** [comment]
Are you happy with this being optional?

**Comment by mvl22** [comment]
I'd prefer a location to be set if possible. Presumably this is equivalent to defaulting to the whole world, i.e. as at present.

Then it can be a mandatory value and keep the database lookups simple.

**Comment by nikolai-b** [comment]
Currently without a location then we can simply not show a map, defaulting to the whole world would mean showing a pointless map or checking if the location was the whole world and not showing the map if it was.  It would also be confusing when coming to edit the library item as you'd start with the whole world, instead of a sensible default.

Currently we don't have a feature to search for library items by location so there is no database lookup but I assume that is coming.

**Comment by nikolai-b** [comment]
P.S. this is on staging already via
https://github.com/cyclestreets/cyclescape/commit/7c0398cc so hopefully this can be closed soon

**Comment by mvl22** [comment]
> Currently we don't have a feature to search for library items by location so there is no database lookup but I assume that is coming.

The intention is that the library item match on the thread screen would be filtered by a match on the geometries.

For this reason, it makes sense for existing items to have a worldwide geometry. If the editing link is clear that will motivate us to adjust existing items.

**Comment by nikolai-b** [comment]
Sorry I disagree.  If a library item has a worldwide location that could be intentional or it could be because we had set it as worldwide.  If you want to do a match issue geometries  with library item geometries that sounds like another issue and we can discus how best to do that there but this issue was about adding location to library items, which I believe is done.
