### ISSUE TITLE
Fault with 'paste' plugin

### ISSUE THREAD

**Issue by CHCausier** [cyclestreets/cyclescape#877]
![image](https://user-images.githubusercontent.com/5610643/64691144-ea6b0100-d489-11e9-8b1d-bd7d98778124.png)

I get this red box on each new thread page on Cyclescape.  I'm accessing via Chrome on a Windows Desktop.

**Comment by nikolai-b** [comment]
@CHCausier sorry about that.  Sadly on my version of chrome everything works fine so I have a few more questions (I tried Windows 8.1 and Chrome 75).  
1. What [Windows version](https://support.microsoft.com/en-gb/help/13443/windows-which-version-am-i-running) are you on and what version of [chrome](https://www.whatversion.net/chrome/)? 
1. Does this still happen when you visit the site?  
1. Have you used the site before, and if so did it happen then?

Thanks

**Comment by mvl22** [comment]
iOS is giving this rather than an editable text area. Clicking on the icon opens a full screen editor but this doesn’t seem submittable.

Might be worth reverting the TinyMCE plugin version.

![24A15581-9926-4589-860E-12B598E53D69](https://user-images.githubusercontent.com/361423/64882178-e17e5900-d65c-11e9-8450-64bcea24f0fc.png)

**Comment by nikolai-b** [comment]
I've moved tinymce to an earlier version.  Please @CHCausier could you let me know if this fixes your issue? Thanks

**Comment by CHCausier** [comment]
I'll see if I can check again on Monday (it's not a problem on my non-work
configuration of Firefox & Windows 10)

**Comment by nikolai-b** [comment]
Please re-open this if it is still a problem.
