### ISSUE TITLE
Issues drop-down in thread editing page needs truncation

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#907]
On the thread properties page, the entries in the issues drop down need truncation applied.

![Screen Shot 2020-01-04 at 23 25 16](https://user-images.githubusercontent.com/361423/71772801-95c42800-2f49-11ea-8acd-04a05869cf7b.png)

Although this isn't really a good UI anyway, at least we should make what is there not be broken.

**Comment by nikolai-b** [comment]
Looking at the code the issue is bigger, currently the select box has all issues the user has access to, in the case I tried there were over 6000.  Really I think we should replace this with a [select2](https://select2.org) and fetch the data remotely but that is a fair chunk of work.  It would allow us to change most selects to select2.  What are your thoughts @mvl22 ?

**Comment by mvl22** [comment]
This isn't a major issue - I'd prefer for now we just add truncation here as that will be simple.

**Comment by mvl22** [comment]
Good to go live obviously. Much better now.
