### ISSUE TITLE
/api/issues fails to match issues if too zoomed in

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#941]
Issue 1987 appears in this API call:
/api/issues?bbox=0.135727,52.206574,0.145144,52.208996
and its centre point is within that bounding box.

However, if I zoom in towards that centre point, i.e.:
/api/issues?bbox=0.137320,52.207092,0.143000,52.208553
it is no longer present.

I think this is because the issues API is filtering for issues fully enclosed, rather than overlaps.

This is a painful bug for the StreetFocus site. E.g. see:
https://www.streetfocus.uk/proposals/#15.65/52.207998/0.140937
and then zoom in. Issues gradually disappear, which is very odd.

**Comment by mvl22** [comment]
I suspect it's this which needs to be changed:
https://github.com/cyclestreets/cyclescape/blob/staging/app/api/route/issue_api.rb#L79

**Comment by nikolai-b** [comment]
This is done by design or else it doesn't match the issue map on the website.  If an issue covers the bounding box then we don't display it: c0890f55f758ad6b7e7a718d78a091ff4fa01cfe

The problem with showing issues outside the bounding box is large issues then dominate the display, e.g.  
https://www.cyclescape.org/issues/3363-dft-consultations
https://www.cyclescape.org/issues/2681-rumble-strips-instead-of-paint
https://www.cyclescape.org/issues/3343-rate-my-route-software-app-ideas-anyone

The code change is tiny as you point out but I'm not sure it is the right thing.  We could add it as a parameter or we could do something like:

```SQL
WHERE ST_DWithin(
  ST_Centroid(issue.location),
  bounding_box,
  sqrt(ST_Area(bounding_box))/10
)
```
so return issues where the centre of the issue is in the bounding box with a 10% buffer which might make a bit more sense, what do you think?

**Comment by mvl22** [comment]
Ah, I see.

I don't think a buffer is the right solution. I don't get the sense that 10% will remove that zoom effect.

I think a parameter is the best option. Not sure what to call it - any ideas? (Do just go ahead with something!)

**Comment by nikolai-b** [comment]
Not just a buffer but also `ST_Centroid` so if the centre of the issue was within a buffer. That way we skip the covered by / intersect problem.

**Comment by mvl22** [comment]
Happy with any solution that works!
